
# ---------------------------------------------------------------
# Themes
# https://github.com/topics/jekyll-theme?o=desc&s=stars
# ---------------------------------------------------------------

theme: jekyll-theme-slate

# ---------------------------------------------------------------
# Plugins
# Fast math rendering:  https://katex.org/docs/autorender.html
# ---------------------------------------------------------------

markdown: kramdown
kramdown:
    math_engine: katex

