
# ---------------------------------------------------------------
# Themes
# https://github.com/topics/jekyll-theme?o=desc&s=stars
# ---------------------------------------------------------------

theme: jekyll-theme-slate

# ---------------------------------------------------------------
# Plugins
# ---------------------------------------------------------------

mathjax: true

